import {
  emptyInputSchema,
  ipcChannels,
  type PiDesktopApi,
} from '../shared/contracts/ipc';
import {
  browserAnnotationCreateInputSchema,
  browserAnnotationDismissInputSchema,
  browserAnnotationListSchema,
  browserAnnotationRemoveInputSchema,
  browserAnnotationSchema,
  browserAnnotationUpdateInputSchema,
  browserBoundsSchema,
  browserConfirmationResponseSchema,
  browserControlLevelInputSchema,
  browserEventBatchSchema,
  browserHistoryInputSchema,
  browserLinkContextMenuInputSchema,
  browserLinkContextMenuResultSchema,
  browserNavigateInputSchema,
  browserNewTabInputSchema,
  browserWebUrlSchema,
  browserOperationResultSchema,
  browserOriginGrantSchema,
  browserOriginInputSchema,
  browserOverlayInputSchema,
  browserSetDeviceEmulationInputSchema,
  browserSnapshotInputSchema,
  browserStateSchema,
  browserTabIdInputSchema,
  browserUiModeInputSchema,
  browserVisibilityInputSchema,
  semanticPageSnapshotSchema,
} from '../shared/contracts/browser';
import { invoke, subscribe, discardResult } from './transport';

export const browserApi = {
  initializeBrowser: () => invoke(ipcChannels.browserInitialize, emptyInputSchema, browserStateSchema),
  getBrowserState: () => invoke(ipcChannels.browserGetState, emptyInputSchema, browserStateSchema),
  setBrowserBounds: (bounds) => invoke(ipcChannels.browserSetBounds, browserBoundsSchema, browserStateSchema, bounds),
  setBrowserVisible: (visible) => invoke(ipcChannels.browserSetVisible, browserVisibilityInputSchema, browserStateSchema, { visible }),
  setBrowserOverlayBlocked: (blocked) => invoke(ipcChannels.browserSetOverlay, browserOverlayInputSchema, browserStateSchema, { blocked }),
  navigateBrowser: (url) => invoke(ipcChannels.browserNavigate, browserNavigateInputSchema, browserStateSchema, { url }),
  showBrowserLinkContextMenu: (url) => invoke(ipcChannels.browserShowLinkContextMenu, browserLinkContextMenuInputSchema, discardResult(browserLinkContextMenuResultSchema), { url }),
  onBrowserLinkOpen: (listener) => subscribe(ipcChannels.browserOpenLink, browserWebUrlSchema, listener),
  openBrowserLocalFile: () => invoke(ipcChannels.browserOpenLocalFile, emptyInputSchema, browserStateSchema.nullable()),
  createBrowserTab: (initialUrl) => invoke(ipcChannels.browserNewTab, browserNewTabInputSchema, browserStateSchema, initialUrl ? { initialUrl } : {}),
  activateBrowserTab: (tabId) => invoke(ipcChannels.browserActivateTab, browserTabIdInputSchema, browserStateSchema, { tabId }),
  closeBrowserTab: (tabId) => invoke(ipcChannels.browserCloseTab, browserTabIdInputSchema, browserStateSchema, { tabId }),
  controlBrowserHistory: (action) => invoke(ipcChannels.browserHistory, browserHistoryInputSchema, browserStateSchema, { action }),
  setBrowserMode: (mode) => invoke(ipcChannels.browserSetMode, browserUiModeInputSchema, browserStateSchema, { mode }),
  setBrowserDeviceEmulation: (emulation) => invoke(ipcChannels.browserSetDeviceEmulation, browserSetDeviceEmulationInputSchema, browserStateSchema, { emulation }),
  setBrowserControlLevel: (level) => invoke(ipcChannels.browserSetControlLevel, browserControlLevelInputSchema, browserStateSchema, { level }),
  setBrowserOriginGrant: (grant) => invoke(ipcChannels.browserSetGrant, browserOriginGrantSchema, browserStateSchema, grant),
  revokeBrowserOriginGrant: (origin) => invoke(ipcChannels.browserRevokeGrant, browserOriginInputSchema, browserStateSchema, { origin }),
  snapshotBrowser: (input = {}) => invoke(ipcChannels.browserSnapshot, browserSnapshotInputSchema, semanticPageSnapshotSchema, input),
  selectBrowserAnnotation: (kind, comment) => invoke(ipcChannels.browserSelectAnnotation, browserAnnotationCreateInputSchema, browserAnnotationSchema, { kind, comment }),
  listBrowserAnnotations: () => invoke(ipcChannels.browserListAnnotations, emptyInputSchema, browserAnnotationListSchema),
  updateBrowserAnnotation: (id, comment) => invoke(ipcChannels.browserUpdateAnnotation, browserAnnotationUpdateInputSchema, browserAnnotationSchema, { id, comment }),
  removeBrowserAnnotation: (id) => invoke(ipcChannels.browserRemoveAnnotation, browserAnnotationRemoveInputSchema, browserOperationResultSchema, { id }).then((result) => result.ok),
  dismissBrowserAnnotations: (ids) => invoke(ipcChannels.browserDismissAnnotations, browserAnnotationDismissInputSchema, browserOperationResultSchema, { ids }).then((result) => result.ok),
  highlightBrowserAnnotation: (id) => invoke(ipcChannels.browserHighlightAnnotation, browserAnnotationRemoveInputSchema, browserOperationResultSchema, { id }).then((result) => result.ok),
  respondToBrowserConfirmation: (id, approved) => invoke(ipcChannels.browserRespondConfirmation, browserConfirmationResponseSchema, browserOperationResultSchema, { id, approved }).then((result) => result.ok),
  onBrowserEvents: (listener) => subscribe(ipcChannels.browserEvents, browserEventBatchSchema, listener),
} satisfies Partial<PiDesktopApi>;
