import {
  emptyInputSchema,
  ipcChannels,
  musicClearResultSchema,
  musicDurationsEventSchema,
  musicLoadInputSchema,
  musicQueueResultSchema,
  musicStatusSchema,
  musicStreamResultSchema,
  musicTrackInputSchema,
  speechCancelResultSchema,
  speechDownloadProgressSchema,
  speechHotkeyStatusSchema,
  speechModelInputSchema,
  speechStatusSchema,
  speechStreamFeedInputSchema,
  speechStreamStartInputSchema,
  speechStreamUpdateSchema,
  speechTranscribeInputSchema,
  speechTranscriptionSchema,
  voiceHotkeyEventSchema,
  type PiDesktopApi,
} from '../shared/contracts/ipc';
import { invoke, subscribe, ignoreResult, unwrapResult } from './transport';

export const mediaApi = {
  getSpeechStatus: () => invoke(ipcChannels.speechGetStatus, emptyInputSchema, speechStatusSchema),
  ensureSpeechModel: (modelId) => invoke(ipcChannels.speechEnsureModel, speechModelInputSchema, ignoreResult, { modelId }),
  downloadSpeechModel: (modelId) => invoke(ipcChannels.speechDownloadModel, speechModelInputSchema, speechStatusSchema, { modelId }),
  cancelSpeechModelDownload: (modelId) => invoke(ipcChannels.speechCancelDownload, speechModelInputSchema, speechCancelResultSchema, { modelId }).then((result) => result.cancelled),
  removeSpeechModel: (modelId) => invoke(ipcChannels.speechRemoveModel, speechModelInputSchema, speechStatusSchema, { modelId }),
  transcribeSpeech: (modelId, audio, language) => invoke(ipcChannels.speechTranscribe, speechTranscribeInputSchema, speechTranscriptionSchema, { modelId, audio, language }),
  cancelSpeechTranscription: () => invoke(ipcChannels.speechCancel, emptyInputSchema, speechCancelResultSchema).then((result) => result.cancelled),
  startSpeechStream: (modelId, language, refine) => invoke(ipcChannels.speechStreamStart, speechStreamStartInputSchema, ignoreResult, { modelId, language, refine }),
  feedSpeechStream: (audio) => invoke(ipcChannels.speechStreamFeed, speechStreamFeedInputSchema, ignoreResult, { audio }),
  stopSpeechStream: () => invoke(ipcChannels.speechStreamStop, emptyInputSchema, ignoreResult),
  cancelSpeechStream: () => invoke(ipcChannels.speechStreamCancel, emptyInputSchema, ignoreResult),
  getSpeechHotkeyStatus: () => invoke(ipcChannels.speechHotkeyStatus, emptyInputSchema, speechHotkeyStatusSchema),
  onSpeechDownload: (listener) => subscribe(ipcChannels.speechEvents, speechDownloadProgressSchema, listener),
  onSpeechStreamUpdate: (listener) => subscribe(ipcChannels.speechStreamEvents, speechStreamUpdateSchema, listener),
  onVoiceHotkey: (listener) => subscribe(ipcChannels.voiceHotkey, voiceHotkeyEventSchema, listener),
  getMusicStatus: () => invoke(ipcChannels.musicGetStatus, emptyInputSchema, musicStatusSchema),
  loadMusic: (url) => invoke(ipcChannels.musicLoad, musicLoadInputSchema, musicQueueResultSchema, { url }).then(unwrapResult),
  resolveMusicTrack: (trackId) => invoke(ipcChannels.musicResolveTrack, musicTrackInputSchema, musicStreamResultSchema, { trackId }).then(unwrapResult),
  clearMusicQueue: () => invoke(ipcChannels.musicClearQueue, emptyInputSchema, musicClearResultSchema).then((result) => { if (!result.ok) throw new Error(JSON.stringify(result.error)); }),
  onMusicDurations: (handler) => subscribe(ipcChannels.musicDurations, musicDurationsEventSchema, handler),
} satisfies Partial<PiDesktopApi>;
