import {
  skinCatalogSchema,
  skinExportResultSchema,
  skinImportResultSchema,
  skinPackRequestSchema,
} from '../shared/skins';
import {
  appCommandSchema,
  appInfoSchema,
  appSettingsSchema,
  skinRemovalResultSchema,
  emptyInputSchema,
  getAppInfoInputSchema,
  ipcChannels,
  logListSchema,
  mcpServerListSchema,
  mcpProbeInputSchema,
  mcpProbeResultSchema,
  piMigrationReportSchema,
  piMigrationResultSchema,
  openUpdateDownloadResultSchema,
  updateDownloadProgressSchema,
  updateInstallStartedSchema,
  updateVersionInputSchema,
  themeCatalogSchema,
  updateCheckResultSchema,
  windowControlInputSchema,
  windowStateSchema,
  diagnosticsSchema,
  type PiDesktopApi,
} from '../shared/contracts/ipc';
import { invoke, subscribe, ignoreResult, discardResult } from './transport';

export const preferencesApi = {
  getAppInfo: () => invoke(ipcChannels.systemGetInfo, getAppInfoInputSchema, appInfoSchema),
  controlWindow: (action) => invoke(ipcChannels.windowControl, windowControlInputSchema, windowStateSchema, { action }),
  getWindowState: () => invoke(ipcChannels.windowGetState, emptyInputSchema, windowStateSchema),
  newWindow: () => invoke(ipcChannels.windowNew, emptyInputSchema, ignoreResult),
  onWindowState: (listener) => subscribe(ipcChannels.windowState, windowStateSchema, listener),
  getSettings: () => invoke(ipcChannels.settingsGet, emptyInputSchema, appSettingsSchema),
  setSettings: (settings) => invoke(ipcChannels.settingsSet, appSettingsSchema, appSettingsSchema, settings),
  getMcpServers: () => invoke(ipcChannels.mcpGet, emptyInputSchema, mcpServerListSchema),
  setMcpServers: (servers) => invoke(ipcChannels.mcpSet, mcpServerListSchema, mcpServerListSchema, servers),
  testMcpServer: (name) => invoke(ipcChannels.mcpProbe, mcpProbeInputSchema, mcpProbeResultSchema, { name }),
  inspectPiMigration: () => invoke(ipcChannels.piMigrationInspect, emptyInputSchema, piMigrationReportSchema),
  importPiMigration: () => invoke(ipcChannels.piMigrationImport, emptyInputSchema, piMigrationResultSchema),
  checkForUpdates: () => invoke(ipcChannels.updatesCheck, emptyInputSchema, updateCheckResultSchema),
  openUpdateDownload: () => invoke(ipcChannels.updatesOpenDownload, emptyInputSchema, discardResult(openUpdateDownloadResultSchema)),
  downloadAndInstallUpdate: (version) => invoke(ipcChannels.updatesDownloadInstall, updateVersionInputSchema, discardResult(updateInstallStartedSchema), { version }),
  onUpdatesProgress: (listener) => subscribe(ipcChannels.updatesProgress, updateDownloadProgressSchema, listener),
  getSkins: () => invoke(ipcChannels.skinsGet, emptyInputSchema, skinCatalogSchema),
  importSkinPack: () => invoke(ipcChannels.skinsImport, emptyInputSchema, skinImportResultSchema),
  removeSkinPack: (id) => invoke(ipcChannels.skinsRemove, skinPackRequestSchema, skinRemovalResultSchema, { id }),
  exportSkinPack: (id) => invoke(ipcChannels.skinsExport, skinPackRequestSchema, skinExportResultSchema, { id }),
  openSkinsFolder: () => invoke(ipcChannels.skinsOpenFolder, emptyInputSchema, skinExportResultSchema),
  getThemes: () => invoke(ipcChannels.themesGet, emptyInputSchema, themeCatalogSchema),
  getDiagnostics: () => invoke(ipcChannels.diagnosticsGet, emptyInputSchema, diagnosticsSchema),
  getLogs: () => invoke(ipcChannels.logsGet, emptyInputSchema, logListSchema),
  onAppCommand: (listener) => subscribe(ipcChannels.appCommand, appCommandSchema, listener),
} satisfies Partial<PiDesktopApi>;
