import {
  abortResultSchema,
  compactInputSchema,
  emptyInputSchema,
  ipcChannels,
  piEventBatchSchema,
  promptAcceptanceSchema,
  promptInputSchema,
  promptOptimizationInputSchema,
  promptOptimizationResultSchema,
  queueMutationInputSchema,
  queueMutationResultSchema,
  runtimeStateSchema,
  sessionEntryInputSchema,
  sessionIdInputSchema,
  sessionRenameInputSchema,
  sessionDirectMessageInputSchema,
  forkSessionResultSchema,
  navigateSessionBranchResultSchema,
  deleteSessionBranchResultSchema,
  sessionListSchema,
  sessionSearchInputSchema,
  projectPathInputSchema,
  projectSessionListInputSchema,
  projectDeleteSessionsResultSchema,
  subagentControlInputSchema,
  setModelInputSchema,
  setPermissionInputSchema,
  providerLoginStartInputSchema,
  providerLoginRespondInputSchema,
  providerLogoutInputSchema,
  modelsDevAddInputSchema,
  modelsDevListResultSchema,
  modelsDevMutationResultSchema,
  modelsDevProviderDetailSchema,
  modelsDevRemoveInputSchema,
  setThinkingInputSchema,
  type PiDesktopApi,
} from '../shared/contracts/ipc';
import {
  agentTeamControlInputSchema,
} from '../shared/contracts/multiAgent';
import {
  goalMaxClearResultSchema,
  goalMaxControlInputSchema,
  goalMaxCreateInputSchema,
  goalMaxEventBatchSchema,
  goalMaxStateSchema,
  goalMaxSteeringEditInputSchema,
  goalMaxSteeringRemoveInputSchema,
  goalMaxUpdateInputSchema,
} from '../shared/contracts/goalmaxxing';
import {
  taskCreateInputSchema,
  taskDeleteInputSchema,
  taskEventBatchSchema,
  taskListSchema,
  taskReorderInputSchema,
  taskUpdateInputSchema,
} from '../shared/contracts/tasks';
import { invoke, subscribe } from './transport';

export const runtimeApi = {
  getRuntimeState: () => invoke(ipcChannels.runtimeGetState, emptyInputSchema, runtimeStateSchema),
  prompt: (input) => invoke(ipcChannels.runtimePrompt, promptInputSchema, promptAcceptanceSchema, input),
  optimizePrompt: (text, options) => invoke(ipcChannels.runtimeOptimizePrompt, promptOptimizationInputSchema, promptOptimizationResultSchema, { text, advanced: options?.advanced ?? false }),
  abort: () => invoke(ipcChannels.runtimeAbort, emptyInputSchema, abortResultSchema),
  controlSubagent: (input) => invoke(ipcChannels.runtimeControlSubagent, subagentControlInputSchema, runtimeStateSchema, input),
  controlAgentTeam: (input) => invoke(ipcChannels.runtimeControlAgentTeam, agentTeamControlInputSchema, runtimeStateSchema, input),
  setModel: (provider, id) => invoke(ipcChannels.runtimeSetModel, setModelInputSchema, runtimeStateSchema, { provider, id }),
  setThinkingLevel: (level) => invoke(ipcChannels.runtimeSetThinking, setThinkingInputSchema, runtimeStateSchema, { level }),
  setPermissionLevel: (level) => invoke(ipcChannels.runtimeSetPermission, setPermissionInputSchema, runtimeStateSchema, { level }),
  initializeProviderLogin: () => invoke(ipcChannels.runtimeProviderLoginInitialize, emptyInputSchema, runtimeStateSchema),
  startProviderLogin: (input) => invoke(ipcChannels.runtimeProviderLoginStart, providerLoginStartInputSchema, runtimeStateSchema, input),
  respondProviderLogin: (input) => invoke(ipcChannels.runtimeProviderLoginRespond, providerLoginRespondInputSchema, runtimeStateSchema, input),
  cancelProviderLogin: () => invoke(ipcChannels.runtimeProviderLoginCancel, emptyInputSchema, runtimeStateSchema),
  logoutProvider: (providerId) => invoke(ipcChannels.runtimeProviderLogout, providerLogoutInputSchema, runtimeStateSchema, { providerId }),
  listModelsDevProviders: () => invoke(ipcChannels.modelsDevList, emptyInputSchema, modelsDevListResultSchema),
  getModelsDevProvider: (providerId) => invoke(ipcChannels.modelsDevDetail, modelsDevRemoveInputSchema, modelsDevProviderDetailSchema, { providerId }),
  addModelsDevProvider: (input) => invoke(ipcChannels.modelsDevAdd, modelsDevAddInputSchema, modelsDevMutationResultSchema, input),
  removeModelsDevProvider: (providerId) => invoke(ipcChannels.modelsDevRemove, modelsDevRemoveInputSchema, modelsDevMutationResultSchema, { providerId }),
  mutateQueuedMessage: (input) => invoke(ipcChannels.runtimeMutateQueue, queueMutationInputSchema, queueMutationResultSchema, input),
  getGoalMax: () => invoke(ipcChannels.runtimeGoalMaxGet, emptyInputSchema, goalMaxStateSchema.nullable()),
  createGoalMax: (input) => invoke(ipcChannels.runtimeGoalMaxCreate, goalMaxCreateInputSchema, goalMaxStateSchema, input),
  controlGoalMax: (input) => invoke(ipcChannels.runtimeGoalMaxControl, goalMaxControlInputSchema, goalMaxStateSchema, input),
  updateGoalMax: (input) => invoke(ipcChannels.runtimeGoalMaxUpdate, goalMaxUpdateInputSchema, goalMaxStateSchema, input),
  clearGoalMax: () => invoke(ipcChannels.runtimeGoalMaxClear, emptyInputSchema, goalMaxClearResultSchema),
  editGoalMaxSteering: (input) => invoke(ipcChannels.runtimeGoalMaxSteeringEdit, goalMaxSteeringEditInputSchema, goalMaxStateSchema, input),
  removeGoalMaxSteering: (input) => invoke(ipcChannels.runtimeGoalMaxSteeringRemove, goalMaxSteeringRemoveInputSchema, goalMaxStateSchema, input),
  getTaskList: () => invoke(ipcChannels.runtimeTaskGet, emptyInputSchema, taskListSchema.nullable()),
  createTask: (input) => invoke(ipcChannels.runtimeTaskCreate, taskCreateInputSchema, taskListSchema, input),
  updateTask: (input) => invoke(ipcChannels.runtimeTaskUpdate, taskUpdateInputSchema, taskListSchema, input),
  reorderTasks: (input) => invoke(ipcChannels.runtimeTaskReorder, taskReorderInputSchema, taskListSchema, input),
  deleteTask: (input) => invoke(ipcChannels.runtimeTaskDelete, taskDeleteInputSchema, taskListSchema, input),
  clearTasks: () => invoke(ipcChannels.runtimeTaskClear, emptyInputSchema, taskListSchema),
  onTaskEvents: (listener) => subscribe(ipcChannels.runtimeTaskEvents, taskEventBatchSchema, listener),
  onGoalMaxEvents: (listener) => subscribe(ipcChannels.runtimeGoalMaxEvents, goalMaxEventBatchSchema, listener),
  newSession: () => invoke(ipcChannels.runtimeNewSession, emptyInputSchema, runtimeStateSchema),
  listSessions: (query = '') => invoke(ipcChannels.runtimeListSessions, sessionSearchInputSchema, sessionListSchema, { query }),
  listProjectSessions: (projectPath, query = '') => invoke(ipcChannels.projectListSessions, projectSessionListInputSchema, sessionListSchema, { projectPath, query }),
  deleteProjectSessions: (projectPath) => invoke(ipcChannels.projectDeleteSessions, projectPathInputSchema, projectDeleteSessionsResultSchema, { projectPath }),
  switchSession: (sessionId) => invoke(ipcChannels.runtimeSwitchSession, sessionIdInputSchema, runtimeStateSchema, { sessionId }),
  sendSessionMessage: (input) => invoke(ipcChannels.runtimeSendSessionMessage, sessionDirectMessageInputSchema, runtimeStateSchema, input),
  renameSession: (sessionId, name) => invoke(ipcChannels.runtimeRenameSession, sessionRenameInputSchema, runtimeStateSchema, { sessionId, name }),
  deleteSession: (sessionId) => invoke(ipcChannels.runtimeDeleteSession, sessionIdInputSchema, runtimeStateSchema, { sessionId }),
  forkSession: (entryId) => invoke(ipcChannels.runtimeForkSession, sessionEntryInputSchema, forkSessionResultSchema, { entryId }),
  navigateSessionBranch: (entryId) => invoke(ipcChannels.runtimeNavigateSessionBranch, sessionEntryInputSchema, navigateSessionBranchResultSchema, { entryId }),
  deleteSessionBranch: (entryId) => invoke(ipcChannels.runtimeDeleteSessionBranch, sessionEntryInputSchema, deleteSessionBranchResultSchema, { entryId }),
  cloneSession: () => invoke(ipcChannels.runtimeCloneSession, emptyInputSchema, runtimeStateSchema),
  importSession: () => invoke(ipcChannels.runtimeImportSession, emptyInputSchema, runtimeStateSchema.nullable()),
  compact: (instructions) => invoke(ipcChannels.runtimeCompact, compactInputSchema, runtimeStateSchema, { instructions }),
  onEvents: (listener) => subscribe(ipcChannels.runtimeEvents, piEventBatchSchema, listener, (error) => console.error('[fate-ui] dropped a runtime event batch that failed validation', error.message)),
} satisfies Partial<PiDesktopApi>;
