import {
  clipboardTextInputSchema,
  clipboardWriteResultSchema,
  emptyInputSchema,
  fileListInputSchema,
  fileListSchema,
  filePathInputSchema,
  filePreviewSchema,
  fileSearchInputSchema,
  fileSearchResultSchema,
  gitCombinedDiffSchema,
  gitCommitDetailsSchema,
  gitCommitInputSchema,
  gitDiffSchema,
  gitHistorySchema,
  gitOperationInputSchema,
  gitOperationResultSchema,
  gitRevertPathInputSchema,
  gitRevertPathResultSchema,
  sessionExportResultSchema,
  gitStatusSchema,
  gitWorktreeInputSchema,
  gitWorktreeListSchema,
  gitWorktreeSessionResultSchema,
  ipcChannels,
  imageSaveInputSchema,
  imageSaveResultSchema,
  localImageInputSchema,
  openFileResultSchema,
  projectFileReferenceSchema,
  revealProjectResultSchema,
  runtimeImageSchema,
  runtimeStateSchema,
  sessionEntryInputSchema,
  projectPathInputSchema,
  projectOpenInputSchema,
  terminalAckInputSchema,
  terminalCloseInputSchema,
  terminalCreateInputSchema,
  terminalCreateResultSchema,
  terminalEventSchema,
  terminalResizeInputSchema,
  terminalWriteInputSchema,
  type PiDesktopApi,
} from '../shared/contracts/ipc';
import {
  attestationQueryRequestSchema,
  attestationQueryResultSchema,
} from '../shared/contracts/mutationAttestation';
import { invoke, subscribe, ignoreResult, discardResult } from './transport';

export const workspaceApi = {
  selectProject: () => invoke(ipcChannels.projectSelect, emptyInputSchema, runtimeStateSchema),
  openProject: (projectPath, target) => invoke(ipcChannels.projectOpenPath, projectOpenInputSchema, runtimeStateSchema, { projectPath, target }),
  focusProject: (projectPath) => invoke(ipcChannels.projectFocusPath, projectPathInputSchema, runtimeStateSchema, { projectPath }),
  closeProjectRuntime: (projectPath) => invoke(ipcChannels.projectCloseRuntime, projectPathInputSchema, ignoreResult, { projectPath }),
  selectProjectFile: () => invoke(ipcChannels.projectSelectFile, emptyInputSchema, projectFileReferenceSchema),
  revealProject: () => invoke(ipcChannels.projectReveal, emptyInputSchema, revealProjectResultSchema),
  revealProjectPath: (projectPath) => invoke(ipcChannels.projectRevealPath, projectPathInputSchema, revealProjectResultSchema, { projectPath }),
  readLocalImage: (path) => invoke(ipcChannels.imageReadLocal, localImageInputSchema, runtimeImageSchema, { path }),
  saveImageAs: (input) => invoke(ipcChannels.imageSaveAs, imageSaveInputSchema, imageSaveResultSchema, input),
  writeClipboardText: (text) => invoke(ipcChannels.clipboardWriteText, clipboardTextInputSchema, discardResult(clipboardWriteResultSchema), { text }),
  listFiles: (path = '') => invoke(ipcChannels.filesList, fileListInputSchema, fileListSchema, { path }),
  searchFiles: (query, limit = 300) => invoke(ipcChannels.filesSearch, fileSearchInputSchema, fileSearchResultSchema, { query, limit }),
  readFile: (path) => invoke(ipcChannels.filesRead, filePathInputSchema, filePreviewSchema, { path }),
  revealFileLink: (path) => invoke(ipcChannels.filesRevealLink, filePathInputSchema, openFileResultSchema, { path }),
  openFile: (path) => invoke(ipcChannels.filesOpen, filePathInputSchema, openFileResultSchema, { path }),
  getGitStatus: () => invoke(ipcChannels.gitStatus, emptyInputSchema, gitStatusSchema),
  getGitDiff: (path) => invoke(ipcChannels.gitDiff, filePathInputSchema, gitDiffSchema, { path }),
  getGitCombinedDiff: () => invoke(ipcChannels.gitCombinedDiff, emptyInputSchema, gitCombinedDiffSchema),
  listGitWorktrees: () => invoke(ipcChannels.gitWorktrees, emptyInputSchema, gitWorktreeListSchema),
  switchGitWorktree: (path) => invoke(ipcChannels.gitSwitchWorktree, gitWorktreeInputSchema, runtimeStateSchema, { path }),
  createWorktreeSession: (entryId) => invoke(ipcChannels.gitCreateWorktreeSession, sessionEntryInputSchema, gitWorktreeSessionResultSchema, { entryId }),
  getGitHistory: () => invoke(ipcChannels.gitHistory, emptyInputSchema, gitHistorySchema),
  getGitCommitDetails: (hash) => invoke(ipcChannels.gitCommitDetails, gitCommitInputSchema, gitCommitDetailsSchema, { hash }),
  runGitOperation: (operation) => invoke(ipcChannels.gitOperation, gitOperationInputSchema, gitOperationResultSchema, { operation }),
  revertGitPath: (path) => invoke(ipcChannels.gitRevertPath, gitRevertPathInputSchema, gitRevertPathResultSchema, { path }),
  exportSession: () => invoke(ipcChannels.sessionExport, emptyInputSchema, sessionExportResultSchema),
  createTerminal: (cols, rows) => invoke(ipcChannels.terminalCreate, terminalCreateInputSchema, terminalCreateResultSchema, { cols, rows }),
  writeTerminal: (id, data) => invoke(ipcChannels.terminalWrite, terminalWriteInputSchema, ignoreResult, { id, data }),
  acknowledgeTerminal: (id, characters) => invoke(ipcChannels.terminalAck, terminalAckInputSchema, ignoreResult, { id, characters }),
  resizeTerminal: (id, cols, rows) => invoke(ipcChannels.terminalResize, terminalResizeInputSchema, ignoreResult, { id, cols, rows }),
  closeTerminal: (id) => invoke(ipcChannels.terminalClose, terminalCloseInputSchema, ignoreResult, { id }),
  queryAttestations: (request) => invoke(ipcChannels.attestationsQuery, attestationQueryRequestSchema, attestationQueryResultSchema, request ?? {}),
  onTerminalEvent: (listener) => subscribe(ipcChannels.terminalEvents, terminalEventSchema, listener),
} satisfies Partial<PiDesktopApi>;
